Update README.md
stepancar-web-programming/2022-fall-lab-portfolio-nguen-thi-mi-tu pull request #1
Opened 2022-11-11 14:09 UTC by jasmine150720

2022-11-11 21:59 UTC, stepancar requested changes
Ожидается PR содержащий все изменения

2022-11-14 09:59 UTC, ducthangchin commented
![image](https://user-images.githubusercontent.com/69846657/201630169-2b6a3d96-9dfd-4906-acd3-bd010583001f.png)
 
Footer should be in the bottom of page when then content length is less than page size. Recommend pattern
![image](https://user-images.githubusercontent.com/69846657/201631154-5b2a69b5-824d-472f-a51b-19bbf4092d6d.png)

2022-11-15 17:56 UTC, jasmine150720 commented
@ducthangchin Thanks for your your cmt. But i dont see ant

2022-11-15 18:03 UTC, ducthangchin commented
> @ducthangchin Thanks for your your cmt. But i dont see any problems with the footer. It always at the bottom of page. Can you pls give more details?

![image](https://user-images.githubusercontent.com/69846657/201992956-2d0b6208-3d11-49db-8dea-c5e7311dc10f.png)

2022-11-16 23:27 UTC, jasmine150720 commented
@ducthangchin 
What size is your screen? I have tried iphone 11 pro max screen/ mac pro 13 inch/dell g3 screen. They both bring the same result that the footer at the end of the page. But I also add flexbox to the footer to make sure it at the end of the page. PLs check it out!
![image](https://user-images.githubusercontent.com/85243027/202314224-4911cd79-6382-4b6e-9ff8-a92251edbc29.png)

2022-11-21 11:39 UTC, jasmine150720 commented
Я воссоздала ПР. Пожалуйста проверите. @stepancar

2022-11-22 01:50 UTC, stepancar commented on assets/js/script.js
> +  fetch('https://api.countapi.xyz/update/jasmine/mouse/?amount=1')
не хватает обработки ошибок

2022-11-22 01:51 UTC, stepancar commented on assets/js/script.js
> +function updateVisitCount(){
Код ниже можно переписать используя async await синтаксис

2022-11-22 01:52 UTC, stepancar commented on assets/js/script.js
> +const constEl = document.getElementById('count');
В коде виден микс разных стилей. Пожалуйста, перед отправкой ПР на ревью убедитесь что все ошибки eslint исправлены

2022-11-22 01:53 UTC, stepancar commented on service.html
> +</html>
Пожалуйста, перед отправкой на ревью убедитесь что код отформатирован должным образом

2022-11-22 01:55 UTC, stepancar commented
Прекрасная визитка!

2022-11-22 03:38 UTC, stepancar commented
@jasmine150720 в ПР не должно быть конфликтов, так как он должен содержать все изменения

2022-11-24 21:54 UTC, jasmine150720 commented on service.html
> +</html>
Could you pls give me more detail? I dont really get it

2022-11-24 21:57 UTC, jasmine150720 commented on assets/js/script.js
> +const constEl = document.getElementById('count');
solved

2022-11-24 21:58 UTC, jasmine150720 commented on assets/js/script.js
> +function updateVisitCount(){
solved

2022-11-25 04:06 UTC, stepancar commented on service.html
> +</html>
Code should be formatted before sending PR for review.
You can notice in this particular example body closing tag placed in the same column as html closing tag which mean code is not formatted.

For that you can use just regular formatter embedded in your IDE

If you use vscode - cmd+shift+p -> format document

2022-11-25 04:10 UTC, stepancar commented on assets/js/script.js
> +    const response = await fetch("https://api.countapi.xyz/update/jasmine/mouse/?amount=1")
В это сценирии будет лучше отказаться от promise совсем. это повысит читаемость вашего кода

2022-11-25 04:13 UTC, stepancar commented on assets/js/script.js
> +const activeHeader = function () {
Функция выше объявлена иначе, не хватает выдержанной стилистиски в написанном коде.

Я бы рекомендовал пользоваться обычным объявлением
```
function activeHeader() {
}
```

2022-11-25 04:14 UTC, stepancar commented on assets/js/script.js
> +const activeHeader = function () {
Называние функции не совсем отражает что именно она делает

2022-11-25 04:15 UTC, stepancar commented on contact.html
> +      <p class="text-center">&copy; 2022 copyright all right reserved</p>
Давайте сделаем так чтобы открыв страницу в 2023 она показывала корректный год, без необходимости править код

2022-11-25 04:17 UTC, stepancar commented on service.html
> +  <footer class="footer">
Этот блок продублирован на всех страницах.
Дубль кода - потенциальные ошибки при поддержке. Для защиты лаборатоной предлагается решить эту проблему

2024-02-22 11:02 UTC, closed without merging